# Default Arguments for pyfhd
# ~ returns None in Python (i.e. NULL)
input-path: '.'
recalculate-all: false
silent: false
log-file: true
conserve-memory: true
memory-threshold: 1e9
n-pol: 2
FoV: ~
kbinsize: 0.5
dimension: 2048
elements: 2048
min-baseline: 1.
deproject-w-term: ~

# Checkpointing
save-checkpoints: true
obs-checkpoint: true
beam-checkpoint: true
calibrate-checkpoint: true
gridding-checkpoint: true

# Instrument
instrument: 'mwa'
override-target-phasera: ~
override-target-phasedec: ~

# Beam Setup
recalculate-beam: false
interpolate-kernel: true
# options for an FHD saved beam:
saved-beam-file-path: ~
lazy-load-beam: false
# options for a UVBeam readable file (update the path):
uvbeam-file-path: '../mwa_full_embedded_element_pattern.h5'
uvbeam-freq-buffer: 2e6
# Options for the MWA average embedded element beam (JMatrix.fits):
uvbeam-zfile-path: ~ # '../ZMatrix.fits'
uvbeam-mwa-include-cross-feed-coupling: true
# Options for an analytic beam (e.g. short dipole shown here):
analytic-beam-yaml : ~ # "!AnalyticBeam
#   class: ShortDipoleBeam
# "
beam-offset-time: 56
beam-per-baseline: false
beam-nfreq-avg: 16
psf-dim: 14
psf-resolution: 100
beam-mask-threshold: 100
beam-clip-floor: true

# Calibration
calibrate-visibilities: true
# options for choosing sources to go into model visibiliites:
# The calibration catalog file must be readable by pyradiosky's SkyModel object
calibration-catalog-file-path : '../GLEAM_v2_plus_rlb2019.sav'
calibration-model-delay-filter: true
calibration-sidelobe-catalog-file-path: ~
calibration-allow-sidelobe-sources: true
calibration-beam-threshold: ~ # Defaults to 0.05 unless allow-sidelobe-sources is True, in which case the default is 0.01.
calibration-restrict-sources: False
calibration-catalog-flux-threshold: ~
calibration-max-sources: ~
calibration-catalog-refraction: ~
calibration-catalog-spectral-index: ~
calibration-catalog-preserve-zero-spectral-index: false
calibration-collapse-extended-sources: false
calibration-catalog-flatten-spectrum: false
# Use model-file-path to pass in model visibilities. None of the source selection
# options above will be used when passing in model visibilities.
model-file-type: 'sav'  # choices are sav, uvfits and h5 (prefer sav and uvfits)
# If you set model-file-type to uvfits or HDF5, set import-model-uvfits to the (ideally absolute) path of the fits file
# If model-file-type is set to sav then it will look for the sav files as said in the function import_vis_model_from_sav
model-file-path: ~
# options for calibration fitting:
bandpass-calibrate: true
cal-bp-transfer: ~
calibration-polyfit: true
auto-ratio-calibration: true
cable-bandpass-fit: true # Depends on instrument cable length text file
cal-amp-degree-fit: 2
cal-phase-degree-fit: 1
cal-reflection-mode-theory: 150
cal-reflection-mode-delay: false
cal-reflection-hyperresolve: true
cal-reflection-mode-file: false
transfer-calibration: ~
cal-base-gain: ~ # This is set to None by default to set the default based on cal-adaptive-calibration-gain as per FHD
cal-convergence-threshold: 1e-7
cal-time-average: false
calibration-auto-fit: false
calibration-auto-initialize: true
cal-gain-init: 1
min-cal-baseline: 50.
max-cal-baseline: ~
max-cal-iter: 100
cal-adaptive-calibration-gain: false
cal-phase-fit-iter: 4
# Only set to true if you're using MWA data before date 2014-07-23 (23rd July 2014)
digital-gain-jump-polyfit: false
vis-baseline-hist: true
cal-stop: false

# Flagging
time-cut: ~
flag-basic: true
flag-freq-start: ~
flag-freq-end: ~
flag-tiles: []
flag-frequencies: true
flag-model: true
flag-calibration: true
flag-calibration-frequencies: false
flag-visibilities: false
transfer-weights: ~

# Gridding
recalculate-grid: true
mask-mirror-indices: false
image-filter: 'filter_uv_uniform'
grid-spectral: false
grid-weights: true
grid-variance: true
grid-uniform: false

# Deconvolution
# deconvolve : false
# max-deconvolution-components : 20000
# filter-background : true
# smooth-width : 32
dft-threshold : true
# return-decon-visibilities : false
# deconvolution-filter : 'filter_uv_uniform'

# Export
output-path: '.'
# If you don't set description, your run will be named by the run date/time
description: ~  # Add a string name here to name your run
pad-uv-image: 1.
ring-radius-multi: 10.
export-images: true
save-visibilities: true
save-weights: true
save-model: true
save-obs: true
save-params: true
save-cal: true
save-healpix-fits: true
snapshot-healpix-export: true

# Plotting
calibration-plots: true
gridding-plots: true
image-plots: true
log_plots: true
sigma_clipping: 3
percentile_clipping: 1

# Simulation
# run-simulation : false
# in-situ-sim-input : ~
# eor-vis-filepath : ~
# enhance-eor : 1
# sim-noise : ~
# remove-sim-flags : false
# tile-flag-list : ~
# extra-vis-filepath : ~

# HEALPIX
healpix-inds: ~
restrict-healpix-inds: true
split-ps-export: true
ps-kbinsize: 0.5
ps-fov: ~
ps-kspan: 600
ps-dimension: ~
ps-degpix: ~
ps-nfreq-avg: ~
ps-beam-threshold: 0
ps-tile-flag-list: []
n-avg: 2
rephase-weights: true
